ezsystem.database {
  connections: [
    {
      name: "payment"
      url: "jdbc:mysql://103.16.117.223:3306/dev_payment?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC"
      username: "devel"
      password: "Devel@ks35"
      connection-timeout: 10000
      idle-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
    }
  ]
}
