ezsystem.log {
    general {
        stream: false
        error: false
        warning: false
        trace: false
        db: false
        db_error: false
        query: false
        deposit: false
        temp: false
    }

    temp {
    }

    modules {
    }
}